# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'LDRenting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LDRenting
  pod 'IQKeyboardManager'
  pod 'CYLTabBarController'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'SDCycleScrollView', '~> 1.80'
  pod 'lottie-ios', '~> 2.5.2'
  pod 'MBProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'Bugly'
  pod 'TZImagePickerController'
  pod 'AMap2DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  pod 'AFNetworking'
  pod 'MJRefresh'
end
